config/routes.rb
Rails.application.routes.draw do
  resources :video_genres
  resources :genres
  resources :videos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :video_genres
  has_many :videos, through: :video_genres
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :video_genres
  has_many :genres, through: :video_genres

  #NO NEED TO WRITE GENRE_IDS WRITER METHOD! ITS A BUILT IN ACTIVE RECORD METHOD
  #NO NEED TO LOOP THROUGH AND CHECK TO SEE IF IT'S INCLUDED
  # GENRE IDS IS A VERY CLUTCH NAME IT TURNS OUT

  # def genre_ids=(ids)
  #   # binding.pry
  #   # ids.each do |id|
  #   #   genre = Genre.find(id)
  #   #   binding.pry
  #   #   if self.genres.includes?
  #   #   self.genres << genre
  #   # end
  #
  # end
end

app/models/video_genre.rb
class VideoGenre < ApplicationRecord
  belongs_to :video
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to @genre
  end

  def show
    @genre = Genre.find(params[:id])
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/video_genres_controller.rb
class VideoGenresController < ApplicationController
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update]

  def index
    @videos = Video.all
  end

  def show
    #you wrote set_video in the before_action kevin
  end

  def new
    @video = Video.new
    @genres = Genre.all
  end

  def edit
    #you wrote set_video in the before_action kevin
    @genres = Genre.all
  end

  def create
    # {"title": "Red Velvet mix", "genre_ids": ["2", "4"]}
    # genre_ids: originally written as custom overwriting method
    # only to realize that @video.genre_ids is an awesome ActiveRecord Method
    @video = Video.new(video_params)
    @video.save
    redirect_to @video
  end

  def update
    #you wrote set_video in the before_action kevin
    @video.update(video_params)
    redirect_to @video
  end

  private

    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:title, genre_ids: [])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/video_genres_helper.rb
module VideoGenresHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/genres/edit.html.erb
at genre edit page

app/views/genres/index.html.erb
at genre index
<% @genres.each do |genre| %>
  <p><%= genre.name %></p>
<% end %>

app/views/genres/new.html.erb
at new genre page

<%= form_with model: @genre do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.submit %>
<% end %>

app/views/genres/show.html.erb
at genre show
<h1><%=@genre.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Select</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_with model: @video do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.select :genre_ids, @genres.map {|genre| [genre.name, genre.id] }, { include_hidden: false }, { multiple: true, class: "genre-multi-selector" }  %><br>
  <%= f.submit %>
<% end %>

<!-- https://stackoverflow.com/questions/9100808/using-form-for-multi-select-fields-with-acts-as-taggable-on -->
<!-- https://stackoverflow.com/questions/8929230/why-is-the-first-element-always-blank-in-my-rails-multi-select-using-an-embedde -->

<!--
<select multiple="multiple" name="video[genre_ids][]" id="video_genre_ids">
  <option value="2">Rap</option>
  <option value="3">Punk</option>
  <option value="5">Soul</option>
</select>
-->

<!-- <select class="js-example-basic-multiple" name="states[]" multiple="multiple">
  <option value="AL">Alabama</option>
    ...
  <option value="WY">Wyoming</option>
</select> -->

app/views/videos/_form_checkbox.html.erb
<%= form_with model: @video do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <ul>
    <% @genres.each do |genre| %>
      <li>
        <!-- https://medium.com/programming-problem-solving-logbook/rails-multiple-checkboxes-e9c4c7fda356 -->
        <!-- cannot emphasize how important naming the checkboxes genre_ids is, as @video.genre_ids = [1,3,5] makes everything work  -->
        <%= f.check_box(:genre_ids, { multiple: true }, genre.id, false) %>
        <!-- <input type="checkbox" value="4" name="video[genre_ids][]" id="video_genres_4"> "Pop"  -->

        <%= genre.name %>
      </li>
    <% end %>
  </ul>
  <%= f.submit %>
<% end %>

app/views/videos/_form_multiselect.html.erb
<%= form_with model: @video do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.select :genre_ids, @genres.map {|genre| [genre.name, genre.id] }, { include_hidden: false }, { multiple: true }  %>
  <%= f.submit %>
<% end %>

<!-- https://stackoverflow.com/questions/9100808/using-form-for-multi-select-fields-with-acts-as-taggable-on -->
<!-- https://stackoverflow.com/questions/8929230/why-is-the-first-element-always-blank-in-my-rails-multi-select-using-an-embedde -->

<!--
<select multiple="multiple" name="video[genre_ids][]" id="video_genre_ids">
  <option value="2">Rap</option>
  <option value="3">Punk</option>
  <option value="5">Soul</option>
</select>
-->

app/views/videos/edit.html.erb
<h2>Edit Video</h2>

<%= render 'form' %>

app/views/videos/index.html.erb
at video index
<% @videos.each do |video| %>
  <p><%= link_to video.title, video %></p>
<% end %>

app/views/videos/new.html.erb
<h2>New Video</h2>

<%= render 'form' %>

app/views/videos/show.html.erb
<h1><%= @video.title %></h1>

<h3>Genres:</h3>

<% @video.genres.each do |genre| %>
  <%= genre.name %> <br />
<% end %>

<br />

<%=link_to 'Edit', edit_video_path(@video) %> <br>
<%=link_to 'Video Index', videos_path %>